name: Deploy Next.js Web Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo SUPABASE_URL"=${{ secrets.SUPABASE_URL }}" >> .env && echo SUPABASE_ANON_KEY"=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      - name: Build docker image
        run: docker build -t parth7091/atlas-go .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push parth7091/atlas-go:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull parth7091/atlas-go:latest
      - name: Delete old container
        run: docker rm -f atlas-go-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name atlas-go-app-container parth7091/atlas-go 