name: Deploy Next.js Web Application

on:
  push:
    branches:
      - deploy-on-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo SUPABASE_URL"=${{ secrets.SUPABASE_URL }}" >> .env && echo SUPABASE_ANON_KEY"=${{ secrets.SUPABASE_ANON_KEY }}" >> .env && echo DATABASE_URL"=${{ secrets.DATABASE_URL }}" >> .env && echo DIRECT_URL="${{ secrets.DIRECT_URL }}" >> .env && echo KINDE_SITE_URL="${{ secrets.KINDE_SITE_URL }}" >> .env echo KINDE_POST_LOGOUT_REDIRECT_URL="${{ secrets.KINDE_POST_LOGOUT_REDIRECT_URL }}" >> .env echo KINDE_POST_LOGIN_REDIRECT_URL="${{ secrets.KINDE_POST_LOGIN_REDIRECT_URL }}" >> .env
      - name: Build docker Image
        run: docker build -t parth7091/atlas-go .
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Publish image to docker hub
        run: docker push parth7091/atlas-go:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull parth7091/atlas-go:latest
      - name: Delete old container
        run: docker rm -f atlas-go-app-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name atlas-go-app-container parth7091/atlas-go 